language: android

android:
    components:
        - build-tools-19.1.0
        - android-22

before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
    directories:
        - $HOME/.gradle/caches/
        - $HOME/.gradle/wrapper/
